version: '3'
services:
  holorepository-ui-client:
    build:
      context: ./HoloRepositoryUI
      dockerfile: ./client/Dockerfile
      args:
        - REACT_APP_BACKEND_HOST=http://localhost
        - REACT_APP_BACKEND_PORT=3001
        - REACT_APP_BACKEND_TIMEOUT=15000
    ports:
      - "3000:3000"
  holorepository-ui-server:
    build:
      context: ./HoloRepositoryUI
      dockerfile: ./server/Dockerfile
    env_file: ./HoloRepositoryUI/server/.env.local
    ports:
      - "3001:3001"
  holopipelines-core:
    build: ./HoloPipelines
    env_file: ./HoloPipelines/.env
    ports:
      - "3100:3100"
    links:
      - holopipelines-models__dense_vnet_abdominal_ct
      - holostorage-accessor
    environment:
      - MODEL_ABDOMINAL_SEGMENTATION_HOST=http://holopipelines-models__dense_vnet_abdominal_ct
      - HOLOSTORAGE_ACCESSOR_HOST=http://holostorage-accessor
  holostorage-accessor:
    build: ./HoloStorageAccessor
    env_file: ./HoloStorageAccessor/.env
    ports:
      - "3200:3200"
  holopipelines-models__dense_vnet_abdominal_ct:
    build: ./HoloPipelines/models/dense_vnet_abdominal_ct
    ports:
      - "5000:5000"
  holosynthaccess-client:
    build:
      context: ./HoloSynthAccess 
      dockerfile: ./client/Dockerfile
      args:
        - SYNTH_BACKEND_HOST=http://localhost
        - SYNTH_BACKEND_PORT=3005
        - SYNTH_BACKEND_TIMEOUT=15000
    ports:
      - "3005:3005"
  holosynthaccess-server:
    build:
      context: ./HoloSynthAccess
      dockerfile: ./server/Dockerfile
    ports:
      - "3006:3006"
